name: 'Accept to Ship'
description: "Automatically merge a Pull Request with #accept2ship after it's approved."
inputs:
  github-token:
    description: 'GitHub token.'
    required: false
    default: ${{ github.token }}
  merge-method:
    description: 'Merge method to use. Possible values are `merge`, `squash` or `rebase`. Default is merge.'
    required: false
    default: 'merge'
  timeout:
    description: 'The time allowance in seconds for waiting the checks to pass.'
    required: false
    default: 0
  checks-watch-interval:
    description: 'Refresh interval in seconds when using waiting for checks.'
    required: false
    default: 10
  fail-if-timeout:
    description: 'Fail the workflow if timeout.'
    required: false
    default: false
  request-zero-accept-zero:
    description: 'If zero reviews are requested then zero approval are needed.'
    required: false
    default: false
  custom-hashtag:
    description: 'A different hashtag to use other than #accept2ship.'
    required: false
    default: '#accept2ship'
outputs:
  skipped:
    description: 'A boolean that indicates whether the action skipped merging/squashing/rebasing because the conditions are not met.'
runs:
  using: 'node20'
  main: 'bundle/index.js'
branding:
  icon: 'git-merge'
  color: 'green'
