name: "Accept to Ship"
description: "Automatically merge a Pull Request with #accept2ship after it's approved."
inputs:
  github-token:
    description: "GitHub token."
    required: false
    default: ${{ github.token }}
  merge-method:
    description: "Merge method to use. Possible values are `merge`, `squash` or `rebase`. Default is merge."
    required: false
    default: "merge"
  timeout:
    description: "The time allowance for waiting the checks to pass in seconds."
    required: false
    default: 600
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: "green"
