name: "TypeScript Github Action Template"
description: "A template to create custom GitHub Action with TypeScript/JavaScript."
inputs:
  github-token:
    description: "GitHub token."
    required: false
    default: ${{ github.token }}
  merge-method:
    description: "Merge method to use. Possible values are `merge`, `squash` or `rebase`. Default is merge."
    required: false
    default: "merge"
runs:
  using: "node16"
  main: "dist/index.js"
