name: Debug for Dependabot

on:
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  pull_request_review:
    types: [submitted, edited]
  workflow_dispatch:

jobs:
  dependabot-build:
    name: Debug for Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
