name: Fork

on:
  pull_request:
    branches: [main]

jobs:
  fork:
    name: Fork
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit
