name: Ship

on:
  pull_request:
    branches: [master]
    types:
      [
        labeled,
        unlabeled,
        edited,
        closed,
        reopened,
        synchronize,
        review_requested,
        review_request_removed,
      ]
  pull_request_review:
    branches: [master]
    types: [submitted, edited, dismissed]
  check_run:
    branches: [master]
    type: [created, rerequested, completed]
  check_suite:
    branches: [master]
    types: [completed]
  workflow_run:
    branches: [master]
    workflows: ["Build", "Test", "ESLint", "CodeQL"]
    types: [completed]

concurrency:
  group: ${{ github.event.pull_request.number || github.workflow }}
  cancel-in-progress: true

jobs:
  accept-to-ship:
    name: Accept to Ship
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          merge-method: squash
          timeout: 0

  pass-to-ship:
    name: Pass to Ship
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          merge-method: squash
          timeout: 0
          request-zero-accept-zero: true
          custom-hashtag: "#pass2ship"
