name: Accept to Ship

on:
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted, edited]

jobs:
  ship:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          merge-method: squash
