name: Accept to Ship

on:
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted, edited]
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["Build", "Test", "ESLint", "CodeQL"]
    types: [completed]

jobs:
  ship:
    name: Ship
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          merge-method: squash
          timeout: 0
